#!/usr/bin/env python3
# -*- coding: utf-8 -*-
__author__ = "Diego Dorta, Marco Franchi, Michael Pontikes"
__copyright__ = "Copyright (C) 2019-2022 NXP Semiconductors"
__license__ = "BSD-3-Clause"
import os, sys
import argparse
from datetime import date

def executeRakeFile():
    bundlerGenerator = 'bundle exec rake build'
    os.system(bundlerGenerator)

if __name__ == "__main__":
    if (os.path.exists('Rakefile')):
        executeRakeFile()
    else:
        pass
