namespace :build do
task :pdf do
`bundle exec asciidoctor-pdf -a pdf-themesdir=themes -a pdf-theme=custom -a pdf-fontsdir=themes/fonts NXPDemoExperience.adoc -o output/NXPDemoExperience.pdf`
end
task :html do
`bundle exec asciidoctor NXPDemoExperience.adoc -o output/NXPDemoExperience.html`
end
end
desc 'Build all default formats'
task :build => [ 'build:html', 'build:pdf' ]
