////
  Copyright NXP 2020-2021
  Author: Rogerio Silva <rogerio.silva@nxp.com>
  Author: Marco Franchi <marco.franchi@nxp.com>
  Author: Michael Pontikes <michael.pontikes_1@nxp.com>
////

[[how_to_build]]
== How to build the {NAME} application
[IMPORTANT%autofit]
====
The {NAME} is now available in our prebuilt images. There prebuilt images can
be found on https://www.nxp.com/design/software/embedded-software/i-mx-software/embedded-linux-for-i-mx-applications-processors:IMXLINUX?tab=In-Depth_Tab[our website].
====
[NOTE%autofit]
====
All commands below should be run on a host GNU/Linux machine.
====
. If the `repo` utility is not installed, use the commands below to download it:
+
[source,bash]
----
$ mkdir ~/bin
$ curl https://storage.googleapis.com/git-repo-download/repo > ~/bin/repo
$ chmod a+x ~/bin/repo
$ PATH=${PATH}:~/bin
----
+
. Setup the `{YOCTO_RELEASE}` Yocto branch from `{LINUX_LATEST}` release:
+
[source,bash]
----
$ mkdir imx-yocto-bsp
$ cd imx-yocto-bsp
$ repo init -u https://source.codeaurora.org/external/imx/imx-manifest -b imx-linux-honister -m imx-5.15.y-z.x.0.xml
$ repo sync
----
+
. Create the build project folder. Machine names can be found https://www.nxp.com/docs/en/user-guide/IMX_YOCTO_PROJECT_USERS_GUIDE.pdf[here under Section 5]:
+
[source,bash]
----
$ DISTRO=fsl-imx-xwayland MACHINE=<machine name> source imx-setup-release.sh -b build-xwayland
----
+
. Build the image with the following command:
+
[source,bash]
----
$ bitbake imx-image-full
----
+
. Flash the rootfs file to the board. The file can be found at <YOCTO_BUILD_FOLDER>/tmp/deploy/images/<board name>/imx-image-full-<board name>.wic.bz2

=== Adding the {NAME} to custom images

As of L5.4.47_2.2.0, the {NAME} should be downloaded and included by default
when building the imx-image-full image. To add the {NAME} to those builds that do
not include it by default, follow the steps 1 through 3 in the above section
and then follow the steps below.

. Download the `{META}` layer:
+
[source,bash]
----
$ git clone https://source.codeaurora.org/external/imxsupport/meta-nxp-demo-experience ../sources/meta-nxp-demo-experience -b imx_5.15.y
----
+
. Add the following content to the `conf/bblayers.conf`:
+
[source,bash]
----
BBLAYERS += "${BSPDIR}/sources/meta-nxp-demo-experience"
----
+
. Add the following content to the `conf/local.conf` as well:
+
[source,bash]
----
CORE_IMAGE_EXTRA_INSTALL += "nxp-demo-experience"
----
+
. Build the image as normal:
+
[source,bash]
----
$ bitbake imx-image-full
----
+
. Flash the rootfs file to the board. The file can be found at <YOCTO_BUILD_FOLDER>/tmp/deploy/images/<board name>/imx-image-full-<board name>.wic.bz2

<<<
