////
  Copyright NXP 2019-2022
  Author: Marco Franchi <marco.franchi@nxp.com>
////

[[add_new_demo]]
== How to Add a New Demo

[NOTE%autofit]
====
Instructions on how to add demos to the {NAME} and the full demo list can be
found at https://source.codeaurora.org/external/imxsupport/nxp-demo-experience-demos-list[the nxp-demo-experience-demos-list repo].
====

To add a new demo to the NXP Demo Experience, add an entry to the demos.json
file. The following are the elements of an entry:

* name: Name of the demo.
* executable: Executable command to launch de demo.
* source: Link to the source code. (**optional**)
* icon: Icon file to represent the demo. Looks for the icon in the `icon` folder (**optional**)
* screenshot: Screenshot file of the demo. Looks for the image in the `screenshot` folder (**optional**)
* compatible: List of compatible boards.
* description: Description of the demo.

[IMPORTANT%autofit]
====
All the demos must be inside 2 categories, in the example below,
`Camera Preview` is inside `Multimedia` and `Video4Linux2` categories.
====

Example:
[source, console]
    "multimedia":[{
        "Video4Linux2":[{
            "name": "Camera Preview",
            "executable": "/unittests/v4l2/mxc_v4l2_capture",
            "source": "https://source.codeaurora.org/external/imx/imx-test/tree/test/mxc_v4l2_test/mxc_v4l2_capture.c?h=imx_4.14.98_2.0.0_ga",
            "icon": "v4l2_cam_prev_icon.png",
            "screenshot": "v4l2_cam_prev_screenshot.png",
            "compatible": "imx7ulpevk, imx8qmmek",
            "description": "Description of v4l2 camera preview"
        }]
    }]

[NOTE%autofit]
====
After adding the new demo, you can check if the new entry is in a valid JSON
format by copying the entire file text and pasting on the site:
**http://json.parser.online.fr/**
====
<<<
