////
  Copyright NXP 2021-2022
  Author: Michael Pontikes <michael.pontikes_1@nxp.com>
////

[appendix]
== Setting up cameras on i.MX 8M Plus

To use demos that require cameras, there are some required steps to set up the
cameras. To do this, follow the instructions below. This only needs to do be
done when cameras are switched.

*Required Materials*

* A host machine and board
* A microUSB cord that can connect to the host machine
* A terminal that can communicate over a COM port, such as https://ttssh2.osdn.jp/index.html.en[Tera Term]
* https://ftdichip.com/drivers/d2xx-drivers/[COM Drivers] (https://ftdichip.com/drivers/d2xx-drivers/)

=== Setting up the host computer
. Download and install the COM Drivers and terminal (if not installed already)
. In the terminal, set the communication speed to 155200
. Open the terminal and have it communicate with the COM port

=== Setting up the board

[IMPORTANT%autofit]
Do not plug-in or remove the Mini-SAS devices while the board is powered on!
This may cause damage to the board and devices.

. Turn off the board
. Attach the MicroUSB cord between the DEBUG port on the board and the host machine
. Attach the cameras to the board
. If using one camera, connect it to the first CSI MIPI port.
. If using both the OV5640 and Basler cameras, connect the Basler camera to the first CSI port and OV5640 camera to the second CSI port

[WARNING]
The Basler camera requires assembly. Follow the directions included in the box
to assemble the camera. When connecting the MIPI strip, make sure that the blue
side of the connector is facing AWAY from the device.

=== Setting up the cameras
. After turning on the board, quickly hold enter on the host machine’s COM terminal until the U-Boot command line appears
. Type “editenv fdtfile” into the COM terminal and hit enter
. Edit the line of text based on the camera setup, and then hit enter
.. If the OV5640 camera is in use, then change it to “imx8mp-evk.dtb”
.. If the Basler camera is in use, then then change it to “imx8mp-evk-basler.dtb”
.. If both the OV5640 and the Basler camera are in use, then change it to “imx8mp-evk-basler-ov5640.dtb”
. Type “saveenv” and hit enter. Then, type “boot” and hit enter

[NOTE]
If the terminal displays “imx8mpevk login” during step 1, restart the board and
try again. Try pressing enter earlier.

<<<
